# Travis CI Configuration
# ============================================================================

language: generic
addons:
  apt:
    sources:
    - debian-sid
before-script:
  - "sudo apt-get install cabal-install"
  - "cabal update"
  - "cabal install shellcheck"
