title: archboot
author: grm34
logo: /assets/images/logo.png
image: /assets/images/archboot.png
description: Arch Linux Installer
tagline: t.me/archboot
url: https://www.archboot.org
theme: jekyll-theme-slate
show_downloads: True
plugins:
  - jekyll-seo-tag
github:
  zip_url: https://github.com/grm34/archboot/archive/v2.8.5.zip
  tar_url: https://github.com/grm34/archboot/archive/v2.8.5.tar.gz
