title: <a href="https://grm34.github.io/archboot/"><img src="https://raw.githubusercontent.com/grm34/archboot/gh-pages/assets/images/logo.png"></a>
description: Arch Linux auto install
theme: jekyll-theme-slate
show_downloads: True
