title: <img src="https://raw.githubusercontent.com/grm34/archboot/gh-pages/assets/images/archboot.png" width="320">
description: Arch Linux Auto Install
theme: jekyll-theme-slate
show_downloads: True
