title: <a href="https://grm34.github.io/archboot/"><img src="https://raw.githubusercontent.com/grm34/archboot/gh-pages/assets/images/logo.png"></a>
description: Arch Linux auto install script @ Gnome - KDE - Deepin - Xfce - LXDE - Cinnamon - Budgie - Enlightenment - MATE - LXQt
theme: jekyll-theme-slate
show_downloads: True
author: grm34
url: https://grm34.github.io/archboot/
plugins:
  - jekyll-seo-tag
