title: <a href="https://grm34.github.io/archboot/"><img src="https://raw.githubusercontent.com/grm34/archboot/gh-pages/assets/images/archboot.png" width="480"></a>
description: Arch Linux Auto Install
theme: jekyll-theme-merlot
show_downloads: True
