title: archboot
description: Arch Linux Installer
author: grm34
tagline: t.me/archboot
url: https://www.archboot.org
logo:
  path: /assets/images/logo.png
image:
  path: /assets/images/archboot.png
theme: jekyll-theme-slate
show_downloads: True
plugins:
  - jekyll-seo-tag
github:
  zip_url: https://github.com/grm34/archboot/archive/v2.8.5.zip
  tar_url: https://github.com/grm34/archboot/archive/v2.8.5.tar.gz
