title: archboot
description: Arch Linux Installer
author: grm34
tagline: t.me/archboot
url: https://www.archboot.org
logo: /assets/images/logo.png
image: /assets/images/logo.png
favicon: /assets/images/favicon.ico
lang: en-US
theme: jekyll-theme-slate
show_downloads: True
plugins:
  - jekyll-seo-tag
github:
  zip_url: https://github.com/grm34/archboot/archive/v2.8.5.zip
  tar_url: https://github.com/grm34/archboot/archive/v2.8.5.tar.gz
